# Generated by Django 5.2.1 on 2025-05-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
            ],
        ),
    ]
