# Generated by Django 5.2.1 on 2025-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('task_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
            ],
        ),
    ]
