# Generated by Django 5.2.1 on 2025-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_task_name_task_estimated_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimated_time',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
